version: '3.9'
services:
  receiver:
    build: ./receiver
    depends_on:
      - "rabbitmq"
    networks:
      - "my-network"

  sender:
    build: ./sender
    ports:
      - "5000:5000"
    depends_on:
      - "rabbitmq"
    networks:
      - "my-network"

  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
    networks:
      - "my-network"

networks:
  my-network:
    driver: bridge